Book/urls.py
from tabnanny import check
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home),
    path("book/<int:book_id>/", views.book),
    path("shop/", views.shop),
    path("books/", views.books),
    path("book/preview/<int:book_id>/", views.preview),
    path("shop/book/<int:book_id>/", views.bookshop),
    path("addtocart/<int:book_id>/", views.addtocart),
    path("cart/", views.cart),
    path("removefromcart/<int:book_id>/", views.removefromcart),
    path("checkout/", views.checkout),
    path("address/<int:order_id>/", views.address),
    path("checkout-session/<int:order_id>/", views.checkout_session),
    path("session-success/", views.session_success),
    #path("/")
]

BookWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Book.urls")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Book/models.py
from pyexpat import model
from typing import Mapping
from django.db import models


class Book(models.Model):
    name = models.CharField(max_length=100)
    author = models.CharField(max_length = 50)
    #publisher = models.CharField(max_length=100, null = True, blank = True)
    short_desc = models.CharField(max_length=200, null = True, blank = True)
    long_desc = models.TextField()
    image = models.ImageField(null = True, blank = True)
    imageshop = models.ImageField(null = True, blank = True)
    externalBuy = models.URLField(null = True, blank = True)
    trailer = models.URLField(null = True, blank = True)
    price = models.FloatField(default = 0)
    
    #make a filter for roudning off if the decimals are only zero

    def __str__(self) -> str:
        return self.name

class BookImage(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    image = models.ImageField(null = True, blank = True)
    def __str__(self) -> str:
        return self.book.name

class BookStoryImage(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    image1 = models.ImageField(null = True, blank = True)
    image2 = models.ImageField(null = True, blank = True)
    image3 = models.ImageField(null = True, blank = True)
    def __str__(self) -> str:
        return self.book.name

class Character(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    name = models.CharField(max_length=40, null = True, blank = True)
    image = models.ImageField(null = True, blank = True)
    def __str__(self) -> str:
        return self.name + " - " + self.book.name

class Address(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    country = models.CharField(max_length=100)
    postcode = models.CharField(max_length=6)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    def __str__(self) -> str:
        return self.firstname + " " + self.lastname

class Order(models.Model):
    amount = models.FloatField(default = 0)
    status = models.CharField(max_length = 50, default = "created")
    address = models.OneToOneField(Address, on_delete=models.CASCADE, null=True, blank=True)
    contactnum = models.CharField(max_length = 15, null = True, blank = True)
    emailid = models.EmailField(null=True,blank=True)
    paymentrefnum = models.CharField(max_length = 100, null = True, blank = True)
    def __str__(self) -> str:
        return str(self.id)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete = models.CASCADE)
    book = models.ForeignKey(Book, on_delete = models.CASCADE)
    quantity = models.IntegerField(default=0)
    def __str__(self) -> str:
        return str(self.order.id) + " "+ self.book.name

Book/views.py
from importlib.metadata import metadata
from statistics import quantiles
from typing import Dict
from django.shortcuts import redirect, render
from gevent import idle
from matplotlib.axis import YAxis
from numpy import empty
from pyparsing import Or
from .models import Address, Book, Order, OrderItem
import stripe

def home(request):
    context = {"books" : Book.objects.all()}
    return render(request, "book/home.html", context)

def book(request, book_id):
    book = Book.objects.get(id = book_id)
    return render(request, "book/bookpage.html", {"book" : book})

def books(request):
    context = {"books" : Book.objects.all()}
    return render(request, "book/books.html", context)

def shop(request):
    context = {"books" : Book.objects.all()}
    return render(request, "book/shop.html", context)

def preview(request, book_id):
    book = Book.objects.get(id = book_id)
    return render(request, "book/preview.html", {"book" : book})

def bookshop(request, book_id):
    book = Book.objects.get(id = book_id)
    return render(request, "book/shopbook.html", {"book" : book})

def addtocart(request, book_id):
    cart = request.session.get("cart")
    # make sure cart exists
    if not cart:
        cart = {}
    quantity = request.POST.get("Quantity")
    if quantity == "":
        return redirect(f"/shop/book/{book_id}/")
    if str(book_id) in cart:
        cart[str(book_id)] = (int(quantity) + int(cart[str(book_id)]))
    else:
        cart[str(book_id)] = int(quantity)
    request.session["cart"] = cart
    print(request.session["cart"])
    return redirect(f"/shop/book/{book_id}/")

def removefromcart(request, book_id):
    cart = request.session.get("cart")
    # make sure cart exists
    if not cart:
        cart = {}
    cart.pop(str(book_id))
    request.session["cart"] = cart
    print(request.session["cart"])
    return redirect("/cart/")
    
def cart(request):
    cart = request.session.get("cart")
    if not cart:
        error = "cart.empty.error"
        return render(request, "book/cart.html", {"error" : error})
    items = []
    total = 0
    for id, quantity in cart.items():
        #id = key, quantity = value
        book = Book.objects.get(pk = id)
        cartitem = {
            "id" : id,
            "name" : book.name,
            "image" : book.image,
            "price" : book.price,
            "quantity" : quantity,
            "booktotal" : quantity * book.price
        }
        items.append(cartitem)
        total += quantity * book.price
    data = {"cart" : items, "total" : total}
    print(items)
    print(total)
    return render(request, "book/cart.html", data)

def checkout(request):
    cart = request.session.get("cart")
    if cart:
        order = Order()
        order.save()
        amount = 0
        for item, quan in cart.items():
            # item = Key
            # quan = Value
            book = Book.objects.get(pk = int(item))
            orderitem = OrderItem(order = order, book = book, quantity = quan)
            orderitem.save()
            amount += int(quan) * book.price
        order.amount = amount
        order.save()
        cart.clear()
        request.session["cart"] = cart
    return redirect(f"/address/{order.id}/")

def address(request, order_id):
    if request.method == "POST":
        data = request.POST
        print(data)

        email = data.get("email")
        contactnum = data.get("contactnum")

        order = Order.objects.get(id = order_id)
        order.emailid = email
        order.contactnum = contactnum
        order.save()

        firstname = data.get("firstname")
        lastname = data.get("lastname")
        country = data.get("country")
        postcode = data.get("postcode")
        city = data.get("city")
        state = data.get("state")

        address = Address(firstname = firstname, lastname = lastname, country = country, postcode = postcode, city = city, state = state)
        address.save()

        order.address = address
        order.save()

        return redirect(f"/checkout-session/{order_id}/")
    return render(request, "book/address.html", {"order": order_id})

def checkout_session(request, order_id):
    order = Order.objects.get(pk = order_id)
    stripe.api_key = "sk_test_51KeD1WDyHhdX3cQPmrSg2O9LDlwhbYeJzO6MYciqj3eULPspSNTx2m2PaZdVZ5K5TZbNgqANvWIqRg1LgETW1jOW00jpZ1hWxZ"
    session = stripe.checkout.Session.create(
        line_items=[{
        'price_data': {
            'currency': 'aud',
            'product_data': {
            'name': "Books",
            },
            'unit_amount': int(order.amount),
        },
        'quantity': 1,
        }],
        metadata = {
            "Order" : order.id
        },

        mode='payment',
        success_url='http://localhost:8000/session-success?session_id={CHECKOUT_SESSION_ID}/',
        cancel_url='http://localhost:8000/session-failure/',
    )
    return redirect(session.url)

def session_success(request):
    sid = request.GET['session_id']
    if sid[-1] == "/":
        sid = sid[:-1]
    print(sid)
    session = stripe.checkout.Session.retrieve(sid)
    order = Order.objects.get(pk = int(session.metadata["Order"]))
    order.status = "paid"
    order.save()
    return render(request, "book/success.html")

Book/templates/book/address.html
{% extends "book/base.html" %}
{% block content %}
<div class = "infopage">   
    <form action = "/address/{{order}}/" method = "post">

        {% csrf_token %}


        <div class = "checkout">

            <h1> CHECK OUT </h1>

        </div>

        <div class = "info">
            <div class = email>

                <label for="email">Your Email ID:</label> <br>
                <input type="text" id="email" name = "email" placeholder="Email ID"> <br>

                <label for="contact" id = "contactlabel">(or your Contact Number):</label> <br>
                <input type="text" id = "contact" placeholder = "Contact Number" name="contactnum"> <br>

            </div>

            <div class = "address">

                <label for="first">Your Address:</label> <br>
                <input type="text" id="first" placeholder="First Name" name = "firstname">

                <input type="text" id="last" placeholder="Last Name" name = "lastname"> <br>

                <input type="text" id="address" placeholder="Unit Number & Street Name" name = "address"> <br>

                <input type="text" id="country" placeholder="Country" name = "country"> <br>

                <input type="text" id="postcode" placeholder="Post Code" name = "postcode">

                <input type="text" id="state" placeholder="State" name = "state">

                <input type="text" id="city" placeholder="City" name = "city"> <br>

                <input type="submit" id="ptpbtn" value="Proceed to Payment">

            </div>
        </div>


    </form>
</div> 
{% endblock %}

Book/templates/book/base.html
<html>
    <head>
        {% load static %}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'book/style.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
        <title> Matthew Rad Books </title>
    </head>

    <body>

        <div class = "header">

            {% load static %}

            <img src="{% static 'book/images/logo.png' %}">

            <div class = "links">
                <a href="/"> Home </a>
                <a href="/books/"> Books </a>
                <a href="/shop/"> Shop </a>
                <a href="https://www.youtube.com/" target="_blank"> Blog </a>
                <a href = "https://www.youtube.com/" target="_blank"> Contact </a>
                <a href="/cart/"> <i class="fa-solid fa-cart-shopping"></i> </a>
            </div>
        </div>
        {% block content %}
            


        {% endblock %}

        <div class = "footer">

            <div class="text">
                <p> Copyright Mehrad Soheilirad © </p>
            </div>

        </div>
    </body>

</html>

Book/templates/book/bookpage.html
{% extends "book/base.html" %}
{% block content %}

    <div class = "bookdetail">

        <h2>{{book.name}}</h2>
        <h3>{{book.author}}</h3>

        <div class = "bookpageimg">
            <img src = "{{book.image.url}}">
        </div>

        <div>
            <p>{{book.long_desc}}</p>
            <h2> AVAILABLE TO BUY HERE: </h2>
            <a href="{{book.externalBuy}}"> Amazon Buy </a>
            <a href="/shop/book/{{book.id}}/"> BUY HERE (Recommended) </a>
            {% for image in book.bookimage_set.all %}
                <img src = "{{image.image.url}}">
            {% endfor %}
            <a href="/book/preview/{{book.id}}/"> READ & EXPLORE THE BOOK </a>
            <h2> MEET THE CHARACTERS </h2>
            {% for character in book.character_set.all %}
            <p> {{character.name}} </p>
            <img src = "{{character.image.url}}">
            {% endfor %}
            <iframe width="1280" height="720" src="{{book.trailer}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            

        </div>
    </div>  

{% endblock %}

Book/templates/book/books.html
{% extends "book/base.html" %}
{% block content %}
    {% for book in books %}
        <a href= "/book/{{book.id}}/">
            <div class = "bookcard">
                <div class = "bookcardimage">
                    <img src = "{{book.image.url}}">
                </div>
                <div class = "bookcardtext">
                    <h2>{{book.name}}</h2>
                </div>
            </div>
        </a>
    {% endfor %}
{% endblock %}

Book/templates/book/cart.html
{% extends "book/base.html" %}
{% block content %}
    <div class = "cartpage">


    <h3> shopping cart </h3>
    <table class = "outertable">
        <tr>
            <th> ITEM </th>
            <th> QUANTITY </th>
            <th> PRICE </th>
            <th> SUB TOTAL </th>
        </tr>
        {% for book in cart %}
            <tr>
                <td class = "innertable">
                    <table>
                        <tr>
                            <td><img src = "{{book.image.url}}"></td>
                            <td>{{book.name}}</td>
                        </tr>
                    </table> </td>
                <td> {{book.quantity}} </td>
                <td> {{book.price}} </td>
                <td> {{book.booktotal}} </td>
                <td> <a href = "/removefromcart/{{book.id}}/"> <i class="fa-solid fa-xmark"></i> </a> </td>
            </tr>
        {% endfor %}
        <tr>
            <td>  </td>
            <td>  </td>
            <td> Total </td>
            <td> {{total}} </td>
        </tr>
    </table>

    <a href="/checkout/"> 
        <button> Check Out </button>
    </a>



    </div>

{% endblock %}

Book/templates/book/home.html
{% extends "book/base.html" %}
{% block content %}
    {% for book in books %}
        <a href= "/book/{{book.id}}/">
            <div class = "bookcard">
                <div class = "bookcardimage">
                    <img src = "{{book.image.url}}">
                </div>

            </div>
        </a>
    {% endfor %}
{% endblock %}

Book/templates/book/preview.html
{% extends "book/base.html" %}
{% block content %}
    {% for bookimage in book.bookstoryimage_set.all %}
        <img src="{{bookimage.image1.url}}">
        <img src="{{bookimage.image2.url}}">
        <img src="{{bookimage.image3.url}}">
    {% endfor %}
    <a href="/book/{{book.id}}/">
        <button> Back </button>
    </a>
{% endblock %}

Book/templates/book/shop.html
{% extends "book/base.html" %}
{% block content %}
    {% for book in books %}
        <a href= "/shop/book/{{book.id}}/">
            <div class = "bookcard">
                <div class = "bookcardimage">
                    {% if book.imageshop %}
                        <img src = "{{book.imageshop.url}}"> 
                    {% else %}
                        <img src = "{{book.image.url}}"> 
                    {% endif %}
                </div>
                <div class = "bookcardtext">
                    <h2>{{book.name}}</h2>
                    <h5>{{book.price}}</h5>
                </div>
            </div>
        </a>
    {% endfor %}
{% endblock %}

Book/templates/book/shopbook.html
{% extends "book/base.html" %}
{% block content %}

    <div class = "bookshopdetail">

        <div class = "bookpageimg">
            <img src = "{{book.image.url}}">
        </div>

        <div class = "bookinfo">
            <h2>{{book.name}}</h2>
            <h5> ${{book.price}} </h5>
            <h3> Written by {{book.author}}</h3>    
            <p>{{book.long_desc}}</p>
            <form action = "/addtocart/{{book.id}}/" method = "POST"> 
                {% csrf_token %}
                <h6 id = "quantitytext">Quantity:</h6>
                <input type="number" name = "Quantity" max = "5" min = "1" value= "0" id = "quantitynumber"> <br>
                <input type="submit" value="Add to Cart" id = "addtocartbutton">   
            </form>

        </div>
    </div>  

    
    <div class = "listimg">
        {% for image in book.bookimage_set.all %}
            <img src = "{{image.image.url}}">
        {% endfor %}
    </div>

{% endblock %}

Book/templates/book/success.html
{% extends "book/base.html" %}
{% block content %}
    <h1>Success!</h1>
{% endblock %}